

create table CHANNEL_CHANNEL_GROUP
(
  CHANNEL_GROUP_ID integer,
  CHANNEL_GROUP_NAME text,
  CHANNEL_ID DOM_FK,
  CHANNEL_CONTENT_PATH text,
  CHANNEL_LANGUAGE text,
  CHANNEL_GROUP_CONTENT_PATH  text
);

create index CCG_GROUP on CHANNEL_CHANNEL_GROUP(CHANNEL_GROUP_ID);
create index CCG_CHANNEL on CHANNEL_CHANNEL_GROUP(CHANNEL_ID);


create view VW_CHANNEL_CHANNEL_GROUP
as select
  CHANNEL_GROUP_ID as CHANNELGROUPID,
  CHANNEL_GROUP_NAME as CHANNELGROUPNAME,
  CHANNEL_ID as CHANNELID,
  CHANNEL_CONTENT_PATH as CHANNELCONTENTPATH,
  CHANNEL_LANGUAGE as CHANNELLANGUAGE,
  CHANNEL_GROUP_CONTENT_PATH as CHANNELGROUPCONTENTPATH
from CHANNEL_CHANNEL_GROUP;



