

create table CHANNEL_CONTENT
(
  ID integer primary key,
  GPS_REGION_ID integer,
  DESTINATION_ID integer,
  PRIORITY smallint,
  HEADING smallint,
  HEADING_VARIANCE smallint,
  AUTO_PRESENT smallint,
  FILLER_DELAY smallint,
  FILLER_CONTINUE_AFTER_INTERRUPT smallint,
  PRESENTED_COUNT smallint,
  MAX_PRESENTED_COUNT smallint,
  ACTIVE_PERIOD_START_DTM date,
  ACTIVE_PERIOD_END_DTM date,
  ACTIVE_PERIOD_IS_SEASON smallint,
  ACTIVE_START_TIME integer, 
  ACTIVE_END_TIME integer,
  ACTIVE_DAYS smallint,
  SUPPRESSED_BY_PARENT smallint,
  HAS_LINKED_CONTENT smallint,
  IS_SEQUENCED smallint,
  SEQUENCE_PRED_IS_COMPLETE smallint,
  SEQUENCE_SUCCESSOR integer,
  SEQUENCE_PREDECESSOR integer,
  SEQUENCE_IS_COMPLETE smallint,
  TRIGGER_TYPE text,
  SPEED_BELOW_THRESHOLD smallint,
  WHILE_SPEED_BELOW_THRESHOLD smallint,
  SPEED_ABOVE_THRESHOLD smallint,
  WHILE_SPEED_ABOVE_THRESHOLD smallint,
  SPEED_THRESHOLD_CAN_RETRIGGER smallint
);

create index CHCT_GPS_REGION on CHANNEL_CONTENT(GPS_REGION_ID);
create index CHCT_TRIGGER_TYPE on CHANNEL_CONTENT(TRIGGER_TYPE);


create view VW_CHANNEL_CONTENT
as select
  ID,
  GPS_REGION_ID as GPSREGIONID,
  DESTINATION_ID as DESTINATIONID,
  PRIORITY,
  HEADING,
  HEADING_VARIANCE as HEADINGVARIANCE,
  AUTO_PRESENT as AUTOPRESENT,
  FILLER_DELAY as FILLERDELAY,
  FILLER_CONTINUE_AFTER_INTERRUPT as FILLERCONTINUEAFTERINTERRUPT,
  PRESENTED_COUNT as PRESENTEDCOUNT,
  MAX_PRESENTED_COUNT as MAXPRESENTEDCOUNT,
  ACTIVE_PERIOD_START_DTM as ACTIVEPERIODSTARTDTM,
  ACTIVE_PERIOD_END_DTM as ACTIVEPERIODENDDTM,
  ACTIVE_PERIOD_IS_SEASON as ACTIVEPERIODISSEASON,
  ACTIVE_START_TIME as ACTIVESTARTTIME,
  ACTIVE_END_TIME as ACTIVEENDTIME,
  ACTIVE_DAYS as ACTIVEDAYS,
  SUPPRESSED_BY_PARENT as SUPPRESSEDBYPARENT,
  HAS_LINKED_CONTENT as HASLINKEDCONTENT,
  IS_SEQUENCED as ISSEQUENCED,
  SEQUENCE_PRED_IS_COMPLETE as SEQUENCEPREDISCOMPLETE,
  SEQUENCE_SUCCESSOR as SEQUENCESUCCESSOR,
  SEQUENCE_PREDECESSOR as SEQUENCEPREDECESSOR,
  SEQUENCE_IS_COMPLETE as SEQUENCEISCOMPLETE,
  TRIGGER_TYPE as TRIGGERTYPE,
  SPEED_BELOW_THRESHOLD as SPEEDBELOWTHRESHOLD,
  WHILE_SPEED_BELOW_THRESHOLD as WHILESPEEDBELOWTHRESHOLD,
  SPEED_ABOVE_THRESHOLD as SPEEDABOVETHRESHOLD,
  WHILE_SPEED_ABOVE_THRESHOLD as WHILESPEEDABOVETHRESHOLD,
  SPEED_THRESHOLD_CAN_RETRIGGER as SPEEDTHRESHOLDCANRETRIGGER
from CHANNEL_CONTENT;



