create table CONTROL_DEFINITION
(
	ID integer not null primary key,
	FORM_ID integer not null,
	NAME text,
	TEXT text,
	DESCRIPTION text,
	GRAPHIC_RESOURCE_NAME text,
	COLOUR text,
	ACTION text,
	ACTION_TARGET text,
	MASTER_AREA_ID integer,
	ACTION_DATA text
);

create view VW_CONTROL_DEFINITION
as select
	ID ,
	FORM_ID as FORMID,
	NAME,
	TEXT,
	DESCRIPTION,
	GRAPHIC_RESOURCE_NAME as GRAPHICRESOURCENAME,
	COLOUR,
	ACTION,
	ACTION_TARGET as ACTIONTARGET,
	MASTER_AREA_ID as MASTERAREAID,
	ACTION_DATA as ACTIONDATA
from CONTROL_DEFINITION;
