

create table CONTENT_ITEM
(
  ID integer primary key,
  CONTENT_TYPE_CODE text,
  FILENAME text,
  CHANNEL_GROUP_ID integer,
  CHANNEL_CONTENT_ID integer,
  DESCRIPTION text,
  IS_FILLER_CONTENT smallint,
  DISPLAY_SEQ integer
);


create index CTI_CONTENT_TYPE on CONTENT_ITEM(CONTENT_TYPE_CODE);
create index CTI_CHANNEL_GROUP on CONTENT_ITEM(CHANNEL_GROUP_ID);
create index CTI_IS_FILLER_CONTENT on CONTENT_ITEM(IS_FILLER_CONTENT);
create index CTI_DISPLAY_SEQ on CONTENT_ITEM(DISPLAY_SEQ);

create view VW_CONTENT_ITEM
as select
  ID,
  CONTENT_TYPE_CODE as CONTENTTYPECODE,
  FILENAME,
  CHANNEL_GROUP_ID as CHANNELGROUPID,
  CHANNEL_CONTENT_ID as CHANNELCONTENTID,
  DESCRIPTION,
  IS_FILLER_CONTENT as ISFILLERCONTENT,
  DISPLAY_SEQ as DISPLAY_SEQ

from CONTENT_ITEM;


