create table DESTINATION_CLASSIFICATION
(
	ID integer not null primary key,
	DESTINATION_TYPE_ID integer,
	NAME text,
	DESCRIPTION text,
	CODE text
);

create view VW_DESTINATION_CLASSIFICATION
as select
	ID,
	DESTINATION_TYPE_ID as DESTINATIONTYPEID,
	NAME,
	DESCRIPTION,
	CODE
from DESTINATION_CLASSIFICATION;

