create table DESTINATION_TYPE
(
	ID integer not null primary key,
	NAME text,
	DESCRIPTION text,
	CODE text,
	COMMENT1_LABEL text,
	COMMENT2_LABEL text,
	COMMENT3_LABEL text,
	COMMENT4_LABEL text,
	ICON_RESOURCE_NAME text
);

create view VW_DESTINATION_TYPE
as select 
	ID,
	NAME,
	DESCRIPTION,
	CODE,
	COMMENT1_LABEL as COMMENT1LABEL,
	COMMENT2_LABEL as COMMENT2LABEL,
	COMMENT3_LABEL as COMMENT3LABEL, 
	COMMENT4_LABEL as COMMENT4LABEL,
	ICON_RESOURCE_NAME as ICONRESOURCENAME
from DESTINATION_TYPE