create table DESTINATION_COLLECTION_MEMBER
(
	COLLECTION_ID integer,
	DESTINATION_ID integer
);

create view VW_DESTINATION_COLLECTION_MEMBER
as select
	COLLECTION_ID as COLLECTIONID,
	DESTINATION_ID as DESTINATION_ID
from DESTINATION_COLLECTION_MEMBER;