CREATE TABLE CHANNEL(  ID integer primary key,  CHANNEL_GROUP_ID integer,  CONTENT_PATH text,  LANGUAGE text);
CREATE TABLE CHANNEL_CHANNEL_GROUP(  CHANNEL_GROUP_ID integer,  CHANNEL_GROUP_NAME text,  CHANNEL_ID DOM_FK,  CHANNEL_CONTENT_PATH text,  CHANNEL_LANGUAGE text,  CHANNEL_GROUP_CONTENT_PATH  text);
CREATE TABLE CHANNEL_CONTENT(  ID integer primary key,  GPS_REGION_ID integer,  DESTINATION_ID integer,  PRIORITY smallint,  HEADING smallint,  HEADING_VARIANCE smallint,  AUTO_PRESENT smallint,  FILLER_DELAY smallint,  FILLER_CONTINUE_AFTER_INTERRUPT smallint,  PRESENTED_COUNT smallint,  MAX_PRESENTED_COUNT smallint,  ACTIVE_PERIOD_START_DTM date,  ACTIVE_PERIOD_END_DTM date,  ACTIVE_PERIOD_IS_SEASON smallint,  ACTIVE_START_TIME integer,   ACTIVE_END_TIME integer,  ACTIVE_DAYS smallint,  SUPPRESSED_BY_PARENT smallint,  HAS_LINKED_CONTENT smallint,  IS_SEQUENCED smallint,  SEQUENCE_PRED_IS_COMPLETE smallint,  SEQUENCE_SUCCESSOR integer,  SEQUENCE_PREDECESSOR integer,  SEQUENCE_IS_COMPLETE smallint,  TRIGGER_TYPE text,  SPEED_BELOW_THRESHOLD smallint,  WHILE_SPEED_BELOW_THRESHOLD smallint,  SPEED_ABOVE_THRESHOLD smallint,  WHILE_SPEED_ABOVE_THRESHOLD smallint,  SPEED_THRESHOLD_CAN_RETRIGGER smallint);
CREATE TABLE CHANNEL_GROUP(  ID integer primary key,  NAME text);
CREATE TABLE CONFIG_PARAMETER(  PARAM_NAME text primary key,  PARAM_VALUE text);
CREATE TABLE CONTENT_ITEM(  ID integer primary key,  CONTENT_TYPE_CODE text,  FILENAME text,  CHANNEL_GROUP_ID integer,  CHANNEL_CONTENT_ID integer,  DESCRIPTION text,  IS_FILLER_CONTENT smallint,  DISPLAY_SEQ integer);
CREATE TABLE CONTROL_DEFINITION
(
	ID integer not null primary key,
	FORM_ID integer not null,
	NAME text,
	TEXT text,
	DESCRIPTION text,
	GRAPHIC_RESOURCE_NAME text,
	COLOUR text,
	ACTION text,
	ACTION_TARGET text,
	MASTER_AREA_ID integer,
	ACTION_DATA text
);
CREATE TABLE DESTINATION
(
	ID integer not null primary key,
	CODE text,
	SHORT_DESCRIPTION text,
	LONG_DESCRIPTION text,
	DESTINATION_TYPE_ID integer,
	CLASSIFICATION_ID integer,
	ARRIVAL_ZONE_DATA text,
	ADDRESS text,
	TELEPHONE_NO text,
	MASTER_AREA_ID integer,
	THEME_ID integer,
	VERSION_NO integer,
	RECOMMENDATION smallint,
	LOCATION text,
	CONDITION text,
	LATITUDE real,
	LONGITUDE real,
	CELL_NO text,
	IMAGE1_FILENAME text,
	IMAGE2_FILENAME text,
	COMMENT1 text,
	COMMENT2 text,
	COMMENT3 text,
	COMMENT4 text,
	BOOKING text,
	'LANGUAGE' text,
	COMMENT text,
	COLLECTION_ID integer,
	ARRIVAL_ZONE_TYPE text,
	ARRIVAL_ZONE_MIN_LATITUDE real,
	ARRIVAL_ZONE_MAX_LATITUDE real,
	ARRIVAL_ZONE_MIN_LONGITUDE real,
	ARRIVAL_ZONE_MAX_LONGITUDE real,
	GRID_REFERENCE_X integer,
	GRID_REFERENCE_Y integer,
	INCLUDE_IN_NEAREST_SEARCH tinyint
);
CREATE TABLE DESTINATION_CLASSIFICATION
(
	ID integer not null primary key,
	DESTINATION_TYPE_ID integer,
	NAME text,
	DESCRIPTION text,
	CODE text
);
CREATE TABLE DESTINATION_COLLECTION
(
	ID integer not null primary key,
	NAME text,
	CODE text
);
CREATE TABLE DESTINATION_COLLECTION_MEMBER
(
	COLLECTION_ID integer,
	DESTINATION_ID integer
);
CREATE TABLE DESTINATION_TYPE
(
	ID integer not null primary key,
	NAME text,
	DESCRIPTION text,
	CODE text,
	COMMENT1_LABEL text,
	COMMENT2_LABEL text,
	COMMENT3_LABEL text,
	COMMENT4_LABEL text,
	ICON_RESOURCE_NAME text
);
CREATE TABLE FORM_DEFINITION
(
	ID integer not null primary key,
	NAME text,
	FORM_TYPE_NAME text,
	TEXT text,
	GRAPHIC_RESOURCE_NAME text,
	MASTER_AREA_ID integer
);
CREATE TABLE GPS_REGION(  ID integer primary key,  REGION_TYPE text,  REGION_DATA  text,  MIN_LONGITUDE FLOAT,  MAX_LONGITUDE FLOAT,  MIN_LATITUDE FLOAT,  MAX_LATITUDE FLOAT,  RESET_ON_ENTRY smallint,  MASTER_AREA_ID integer,  THEME_ID integer, "NAME" TEXT);
CREATE TABLE ITINERARY
(
	ID integer not null primary key,
	FIRST_NAME text,
	LAST_NAME text,
	TITLE text,
	GRACE_PERIOD smallint,
	BOOKING_REFERENCE text,
	GEO_FENCE_DATA text,
	ARRIVAL_DAT datetime,
	DEPARTURE_DAT datetime,
	BRANDING1 text,
	BRANDING2 text,
	BRANDING3 text
);
CREATE TABLE ITINERARY_DAY
(
	ID integer not null primary key,
	ITINERARY_DAT date,
	COMMENT text
);
CREATE TABLE ITINERARY_DESTINATION
(
	ID integer not null primary key,
	ITINERARY_DAY_ID integer,
	DESTINATION_ID integer,
	DESTINATION_ORDER smallint
);
CREATE TABLE MASTER_AREA
(
  ID integer primary key,
  NAME text,
  DESCRIPTION text,
  MIN_LONGITUDE FLOAT,
  MAX_LONGITUDE FLOAT,
  MIN_LATITUDE FLOAT,
  MAX_LATITUDE FLOAT,
  CONTENT_BASE_PATH  text,
  REGION_DATA  text,
  REGION_TYPE text
);
CREATE TABLE MY_SELECTION
(
	DESTINATION_ID integer not null primary key
);
CREATE TABLE RECENT_DESTINATION
(
	VISITED_DAT date not null,
	DESTINATION_ID integer,
	LATITUDE real,
	LONGITUDE real,
	NAME text
);
CREATE TABLE THEME(  ID integer primary key,  NAME text,  DESCRIPTION text);
CREATE TABLE VW_ITINERARY_DAY(
  ID INT,
  ITINERARYDAT NUM,
  COMMENT TEXT
);
CREATE VIEW VW_CHANNEL
as select
  ID,
  CHANNEL_GROUP_ID as CHANNELGROUPID,
  CONTENT_PATH as CONTENTPATH,
  LANGUAGE
from CHANNEL;
CREATE VIEW VW_CHANNEL_CHANNEL_GROUP
as select
  CHANNEL_GROUP_ID as CHANNELGROUPID,
  CHANNEL_GROUP_NAME as CHANNELGROUPNAME,
  CHANNEL_ID as CHANNELID,
  CHANNEL_CONTENT_PATH as CHANNELCONTENTPATH,
  CHANNEL_LANGUAGE as CHANNELLANGUAGE,
  CHANNEL_GROUP_CONTENT_PATH as CHANNELGROUPCONTENTPATH
from CHANNEL_CHANNEL_GROUP;
CREATE VIEW "VW_CHANNEL_CONTENT" AS  select
  ID,
  GPS_REGION_ID as GPSREGIONID,
  DESTINATION_ID as DESTINATIONID,
  PRIORITY,
  HEADING,
  HEADING_VARIANCE as HEADINGVARIANCE,
  AUTO_PRESENT as AUTOPRESENT,
  FILLER_DELAY as FILLERDELAY,
  FILLER_CONTINUE_AFTER_INTERRUPT as FILLERCONTINUEAFTERINTERRUPT,
  PRESENTED_COUNT as PRESENTEDCOUNT,
  MAX_PRESENTED_COUNT as MAXPRESENTEDCOUNT,
  ACTIVE_PERIOD_START_DTM as ACTIVEPERIODSTARTDTM,
  ACTIVE_PERIOD_END_DTM as ACTIVEPERIODENDDTM,
  ACTIVE_PERIOD_IS_SEASON as ACTIVEPERIODISSEASON,
  ACTIVE_START_TIME as ACTIVESTARTTIME,
  ACTIVE_END_TIME as ACTIVEENDTIME,
  ACTIVE_DAYS as ACTIVEDAYS,
  SUPPRESSED_BY_PARENT as SUPPRESSEDBYPARENT,
  HAS_LINKED_CONTENT as HASLINKEDCONTENT,
  IS_SEQUENCED as ISSEQUENCED,
  SEQUENCE_PRED_IS_COMPLETE as SEQUENCEPREDECESSORISCOMPLETE,
  SEQUENCE_SUCCESSOR as SEQUENCESUCCESSOR,
  SEQUENCE_PREDECESSOR as SEQUENCEPREDECESSOR,
  SEQUENCE_IS_COMPLETE as SEQUENCEISCOMPLETE,
  TRIGGER_TYPE as TRIGGERTYPE,
  SPEED_BELOW_THRESHOLD as SPEEDBELOWTHRESHOLD,
  WHILE_SPEED_BELOW_THRESHOLD as WHILESPEEDBELOWTHRESHOLD,
  SPEED_ABOVE_THRESHOLD as SPEEDABOVETHRESHOLD,
  WHILE_SPEED_ABOVE_THRESHOLD as WHILESPEEDABOVETHRESHOLD,
  SPEED_THRESHOLD_CAN_RETRIGGER as SPEEDTHRESHOLDCANRETRIGGER
from CHANNEL_CONTENT;
CREATE VIEW VW_CHANNEL_GROUPas select  ID,  NAMEfrom CHANNEL_GROUP;
CREATE VIEW VW_CONTENT_ITEM
as select
  ID,
  CONTENT_TYPE_CODE as CONTENTTYPECODE,
  FILENAME,
  CHANNEL_GROUP_ID as CHANNELGROUPID,
  CHANNEL_CONTENT_ID as CHANNELCONTENTID,
  DESCRIPTION,
  IS_FILLER_CONTENT as ISFILLERCONTENT,
  DISPLAY_SEQ as DISPLAYSEQ

from CONTENT_ITEM;
CREATE VIEW VW_CONTROL_DEFINITION
as select
	ID ,
	FORM_ID as FORMID,
	NAME,
	TEXT,
	DESCRIPTION,
	GRAPHIC_RESOURCE_NAME as GRAPHICRESOURCENAME,
	COLOUR,
	ACTION,
	ACTION_TARGET as ACTIONTARGET,
	MASTER_AREA_ID as MASTERAREAID,
	ACTION_DATA as ACTIONDATA
from CONTROL_DEFINITION;
CREATE VIEW VW_DESTINATION
as select
	ID,
	CODE,
	SHORT_DESCRIPTION as SHORT_DESCRIPTION,
	LONG_DESCRIPTION as LONG_DESCRIPTION,
	DESTINATION_TYPE_ID as DESTINATIONTYPEID,
	CLASSIFICATION_ID as CLASSIFICATIONID,
	ARRIVAL_ZONE_DATA as ARRIVALZONEDATA,
	ADDRESS,
	TELEPHONE_NO as TELEPHONENO,
	MASTER_AREA_ID as MASTERAREAID,
	THEME_ID as THEMEID,
	VERSION_NO as VERSIONNO,
	RECOMMENDATION,
	LOCATION,
	CONDITION,
	LATITUDE,
	LONGITUDE,
	CELL_NO as CELL_NO,
	IMAGE1_FILENAME as IMAGE1FILENAME,
	IMAGE2_FILENAME as IMAGE2FILENAME,
	COMMENT1,
	COMMENT2,
	COMMENT3,
	COMMENT4,
	BOOKING,
	'LANGUAGE',
	COMMENT,
	COLLECTION_ID as COLLECTIONID,
	ARRIVAL_ZONE_TYPE as ARRIVALZONETYPE,
	ARRIVAL_ZONE_MIN_LATITUDE as ARRIVALZONEMINLATITUDE,
	ARRIVAL_ZONE_MAX_LATITUDE as ARRIVALZONEMAXLATITUDE,
	ARRIVAL_ZONE_MIN_LONGITUDE as ARRIVALZONEMINLONGITUDE,
	ARRIVAL_ZONE_MAX_LONGITUDE as ARRIVALZONEMAXLONGITUDE,
	GRID_REFERENCE_X as GRIDREFERENCEX,
	GRID_REFERENCE_Y as GRIDREFERENCEY,
	INCLUDE_IN_NEAREST_SEARCH as INCLUDEINNEARESTSEARCH
from DESTINATION;
CREATE VIEW VW_DESTINATION_CLASSIFICATION
as select
	ID,
	DESTINATION_TYPE_ID as DESTINATIONTYPEID,
	NAME,
	DESCRIPTION,
	CODE
from DESTINATION_CLASSIFICATION;
CREATE VIEW VW_DESTINATION_COLLECTION
as select
	ID,
	NAME,
	CODE
from DESTINATION_COLLECTION;
CREATE VIEW VW_DESTINATION_COLLECTION_MEMBER
as select
	COLLECTION_ID as COLLECTIONID,
	DESTINATION_ID as DESTINATION_ID
from DESTINATION_COLLECTION_MEMBER;
CREATE VIEW VW_DESTINATION_TYPE
as select 
	ID,
	NAME,
	DESCRIPTION,
	CODE,
	COMMENT1_LABEL as COMMENT1LABEL,
	COMMENT2_LABEL as COMMENT2LABEL,
	COMMENT3_LABEL as COMMENT3LABEL, 
	COMMENT4_LABEL as COMMENT4LABEL,
	ICON_RESOURCE_NAME as ICONRESOURCENAME
from DESTINATION_TYPE;
CREATE VIEW VW_FORM_DEFINITION
as select
	ID,
	NAME,
	FORM_TYPE_NAME as FORMTYPENAME,
	'TEXT',
	GRAPHIC_RESOURCE_NAME as GRAPHICRESOURCENAME,
	MASTER_AREA_ID as MASTERAREAID
from FORM_DEFINITION;
CREATE VIEW VW_GPS_REGION
as select
  ID,
  REGION_TYPE as REGIONTYPE,
  REGION_DATA as REGIONDATA,
  MIN_LONGITUDE as MINLONGITUDE,
  MAX_LONGITUDE as MAXLONGITUDE,
  MIN_LATITUDE as MINLATITUDE,
  MAX_LATITUDE as MAXLATITUDE,
  RESET_ON_ENTRY as RESETONENTRY,
  MASTER_AREA_ID as MASTERAREAID,
  THEME_ID as THEMEID
from GPS_REGION;
CREATE VIEW VW_ITINERARY
as select
	ID,
	FIRST_NAME as FIRSTNAME,
	LAST_NAME as LASTNAME,
	TITLE,
	GRACE_PERIOD as GRACEPERIOD,
	BOOKING_REFERENCE as BOOKINGREFERENCE,
	GEO_FENCE_DATA as GEOFENCEDATA,
	ARRIVAL_DAT as ARRIVALDAT,
	DEPARTURE_DAT as DEPARTUREDAT,
	BRANDING1,
	BRANDING2,
	BRANDING3
from ITINERARY;
CREATE VIEW VW_ITINERARY_DESTINATION
as select
	ID,
	ITINERARY_DAY_ID as ITINERARYDAYID,
	DESTINATION_ID as DESTINATIONID,
	DESTINATION_ORDER as DESTINATIONORDER
from ITINERARY_DESTINATION;
CREATE VIEW VW_MASTER_AREA
as select
  ID,
  NAME,
  DESCRIPTION,
  MIN_LONGITUDE as MINLONGITUDE,
  MAX_LONGITUDE as MAXLONGITUDE,
  MIN_LATITUDE as MINLATITUDE,
  MAX_LATITUDE as MAXLATITUDE,
  CONTENT_BASE_PATH as CONTENTBASEPATH,
  REGION_DATA as REGIONDATA,
  REGION_TYPE as REGIONTYPE
from MASTER_AREA;
CREATE VIEW VW_MY_SELECTION
as select
	DESTINATION_ID as DESTINATIONID
from MY_SELECTION;
CREATE VIEW VW_RECENT_DESTINATION
as select
	VISITED_DAT,
	DESTINATION_ID,
	LATITUDE,
	LONGITUDE,
	NAME text
from RECENT_DESTINATION;
CREATE VIEW VW_THEME
as select
  ID,
  NAME,
  DESCRIPTION
from THEME;
CREATE INDEX CCG_CHANNEL on CHANNEL_CHANNEL_GROUP(CHANNEL_ID);
CREATE INDEX CCG_GROUP on CHANNEL_CHANNEL_GROUP(CHANNEL_GROUP_ID);
CREATE INDEX CHCT_GPS_REGION on CHANNEL_CONTENT(GPS_REGION_ID);
CREATE INDEX CHCT_TRIGGER_TYPE on CHANNEL_CONTENT(TRIGGER_TYPE);
CREATE INDEX CHNL_GROUP on CHANNEL(CHANNEL_GROUP_ID);
CREATE INDEX CTI_CHANNEL_CONTENT on CONTENT_ITEM(CHANNEL_CONTENT_ID);
CREATE INDEX CTI_CHANNEL_GROUP on CONTENT_ITEM(CHANNEL_GROUP_ID);
CREATE INDEX CTI_CONTENT_TYPE on CONTENT_ITEM(CONTENT_TYPE_CODE);
CREATE INDEX CTI_DISPLAY_SEQ on CONTENT_ITEM(DISPLAY_SEQ);
CREATE INDEX CTI_IS_FILLER_CONTENT on CONTENT_ITEM(IS_FILLER_CONTENT);
CREATE INDEX "CTLD_FORM_IDX" ON "CONTROL_DEFINITION" ("FORM_ID" ASC);
CREATE INDEX CTLD_MASTER_AREA_IDX on CONTROL_DEFINITION(MASTER_AREA_ID);
CREATE INDEX DCM_DESTINATION on DESTINATION_COLLECTION_MEMBER(DESTINATION_ID);
CREATE INDEX DST_CLASSIFICATION on DESTINATION(CLASSIFICATION_ID);
CREATE INDEX DST_DESTINATION_TYPE on DESTINATION(DESTINATION_TYPE_ID);
CREATE INDEX DST_GRIDX on DESTINATION(GRID_REFERENCE_X);
CREATE INDEX DST_GRIDY on DESTINATION(GRID_REFERENCE_Y);
CREATE INDEX DST_MASTER_AREA on DESTINATION(MASTER_AREA_ID);
CREATE INDEX "FRMD_MASTER_AREA_IDX" ON "FORM_DEFINITION" ("MASTER_AREA_ID" ASC);
CREATE INDEX "FRMD_NAME_IDX" ON "FORM_DEFINITION" ("NAME" ASC);
CREATE INDEX GPSR_MASTER_AREA_IDX on GPS_REGION(MASTER_AREA_ID);
CREATE INDEX GPSR_REGION_TYPE_IDX on GPS_REGION(REGION_TYPE);
CREATE INDEX GPSR_THEME_IDX on GPS_REGION(THEME_ID);
