

create table GPS_REGION
(
  ID integer primary key,
  REGION_TYPE text,
  REGION_DATA  text,
  MIN_LONGITUDE FLOAT,
  MAX_LONGITUDE FLOAT,
  MIN_LATITUDE FLOAT,
  MAX_LATITUDE FLOAT,
  RESET_ON_ENTRY smallint,
  MASTER_AREA_ID integer,
  THEME_ID integer
);


create index GPSR_REGION_TYPE_IDX on GPS_REGION(REGION_TYPE);
create index GPSR_MASTER_AREA_IDX on GPS_REGION(MASTER_AREA_ID);
create index GPSR_THEME_IDX on GPS_REGION(THEME_ID);



create view VW_GPS_REGION
as select
  ID,
  REGION_TYPE as REGIONTYPE,
  REGION_DATA as REGIONDATA,
  MIN_LONGITUDE as MINLONGITUDE,
  MAX_LONGITUDE as MAXLONGITUDE,
  MIN_LATITUDE as MINLATITUDE,
  MAX_LATITUDE as MAXLATITUDE,
  RESET_ON_ENTRY as RESETONENTRY,
  MASTER_AREA_ID as MASTERAREAID,
  THEME_ID as THEMEID
from GPS_REGION;





