create table ITINERARY_DESTINATION
(
	ID integer not null primary key,
	ITINERARY_DAY_ID integer,
	DESTINATION_ID integer,
	DESTINATION_ORDER smallint
);

create view VW_ITINERARY_DESTINATION
as select
	ID,
	ITINERARY_DAY_ID as ITINERARYDAYID,
	DESTINATION_ID as DESTINATIONID,
	DESTINATION_ORDER as DESTINATIONORDER
from ITINERARY_DESTINATION;

