


create table MASTER_AREA
(
  ID integer primary key,
  NAME text,
  DESCRIPTION text,
  MIN_LONGITUDE FLOAT,
  MAX_LONGITUDE FLOAT,
  MIN_LATITUDE FLOAT,
  MAX_LATITUDE FLOAT,
  CONTENT_BASE_PATH  text,
  REGION_DATA  text,
  REGION_TYPE text
);


create view VW_MASTER_AREA
as select
  ID,
  NAME,
  DESCRIPTION,
  MIN_LONGITUDE as MINLONGITUDE,
  MAX_LONGITUDE as MAXLONGITUDE,
  MIN_LATITUDE as MINLATITUDE,
  MAX_LATITUDE as MAXLATITUDE,
  CONTENT_BASE_PATH as CONTENTBASEPATH,
  REGION_DATA as REGIONDATA,
  REGION_TYPE as REGIONTYPE
from MASTER_AREA;


