create table RECENT_DESTINATION
(
	VISITED_DAT date not null,
	DESTINATION_ID integer,
	LATITUDE real,
	LONGITUDE real,
	NAME text
);



create view VW_RECENT_DESTINATION
as select
	VISITED_DAT as VISITEDDAT,
	DESTINATION_ID as DESTINATIONID,
	LATITUDE,
	LONGITUDE,
	NAME
from RECENT_DESTINATION;
