CREATE TABLE SEARCH_REGION
(
  "ID" integer not null primary key,
  "PARENT_ID" integer,
  "SEARCH_KEY" VARCHAR NOT NULL ,
  "NAME" VARCHAR NOT NULL , 
  "LEVEL" INTEGER NOT NULL,
  "COLLATED_NAME" VARCHAR NOT NULL,
  "LATITUDE" double,
  "LONGITUDE" double,
  STREET_COUNT integer
)

CREATE  INDEX "SR_SEARCH_KEY" ON "SEARCH_REGION" ("SEARCH_KEY" ASC);
CREATE  INDEX "SR_LEVEL" ON "SEARCH_REGION" ("LEVEL" ASC);

