drop VIEW VW_DESTINATION;

CREATE TABLE DESTINATION
(
	ID integer not null primary key,
	CODE text,
	SHORT_DESCRIPTION text,
	LONG_DESCRIPTION text,
	DESTINATION_TYPE_ID integer,
	CLASSIFICATION_ID integer,
	ARRIVAL_ZONE_DATA text,
	ADDRESS text,
	TELEPHONE_NO text,
	MASTER_AREA_ID integer,
	THEME_ID integer,
	VERSION_NO integer,
	RECOMMENDATION smallint,
	LOCATION text,
	CONDITION text,
	LATITUDE real,
	LONGITUDE real,
	CELL_NO text,
	IMAGE1_FILENAME text,
	IMAGE2_FILENAME text,
	COMMENT1 text,
	COMMENT2 text,
	COMMENT3 text,
	COMMENT4 text,
	BOOKING text,
	'LANGUAGE' text,
	COMMENT text,
	COLLECTION_ID integer,
	ARRIVAL_ZONE_TYPE text,
	ARRIVAL_ZONE_MIN_LATITUDE real,
	ARRIVAL_ZONE_MAX_LATITUDE real,
	ARRIVAL_ZONE_MIN_LONGITUDE real,
	ARRIVAL_ZONE_MAX_LONGITUDE real,
	GRID_REFERENCE_X integer,
	GRID_REFERENCE_Y integer,
	INCLUDE_IN_NEAREST_SEARCH tinyint
, "MORE_AD_IMAGE" TEXT, "MORE_AD_TEXT" TEXT, SEARCH_KEY varchar)

CREATE INDEX DST_CLASSIFICATION on DESTINATION(CLASSIFICATION_ID)
CREATE INDEX DST_DESTINATION_TYPE on DESTINATION(DESTINATION_TYPE_ID)
CREATE INDEX DST_GRIDX on DESTINATION(GRID_REFERENCE_X)
CREATE INDEX DST_GRIDY on DESTINATION(GRID_REFERENCE_Y)
CREATE INDEX DST_MASTER_AREA on DESTINATION(MASTER_AREA_ID)